
from django.urls import path , include
from . import views

urlpatterns = [
    path("index" , views.index) ,
    path("login" , views.login) ,
    path("signup" , views.signup) ,
    path("Q_A" , views.Q_A) ,
    path("boardwrite" , views.boardwrite) ,
    path("view1" , views.view1) ,
    path("소개" , views.소개) ,
    path("중랑구" , views.중랑구) ,
    path("동작구" , views.동작구) ,
    path("노량진로" , views.노량진로) ,
    path("매봉로" , views.매봉로) ,
    path("장승배기로" , views.장승배기로) ,
    path("상도로" , views.상도로) ,
    path("동작대로" , views.동작대로) ,
    path("사당로" , views.사당로) ,
    path("만양로" , views.만양로) ,
    path("양천구" , views.양천구) ,
    path("남부순환로" , views.남부순환로) ,
    path("신월로" , views.신월로) ,
    path("목동동로" , views.목동동로) ,
    path("목동서로" , views.목동서로) ,
    path("중앙로" , views.중앙로) ,
    path("오목로" , views.오목로) ,
    path("은평구" , views.은평구) ,
    path("가좌로" , views.가좌로) ,
    path("갈현로" , views.갈현로) ,
    path("불광로" , views.불광로) ,
    path("수색로" , views.수색로) ,
    path("서오릉로" , views.서오릉로) ,
]