from django.shortcuts import render

def index( request ) :
    return render( request , "index.html")
def login( request ) :
    return render( request , "login.html")
def signup( request ) :
    return render( request , "signup.html")
def Q_A( request ) :
    return render( request , "Q_A.html")
def boardwrite( request ) :
    return render( request , "boardwrite.html")
def view1( request ) :
    return render( request , "view1.html")
def 소개( request ) :
    return render( request , "소개.html")
def 중랑구( request ) :
    return render( request , "중랑구.html")
def 동작구( request ) :
    return render( request , "동작구.html")
def 노량진로( request ) :
    return render( request , "노량진로.html")
def 매봉로( request ) :
    return render( request , "매봉로.html")
def 장승배기로( request ) :
    return render( request , "장승배기로.html")
def 상도로( request ) :
    return render( request , "상도로.html")
def 동작대로( request ) :
    return render( request , "동작대로.html")
def 사당로( request ) :
    return render( request , "사당로.html")
def 만양로( request ) :
    return render( request , "만양로.html")
def 양천구( request ) :
    return render( request , "양천구.html")
def 남부순환로( request ) :
    return render( request , "남부순환로.html")
def 신월로( request ) :
    return render( request , "신월로.html")
def 목동동로( request ) :
    return render( request , "목동동로.html")
def 목동서로( request ) :
    return render( request , "목동서로.html")
def 중앙로( request ) :
    return render( request , "중앙로.html")
def 오목로( request ) :
    return render( request , "오목로.html")
def 은평구( request ) :
    return render( request , "은평구.html")
def 가좌로( request ) :
    return render( request , "가좌로.html")
def 갈현로( request ) :
    return render( request , "갈현로.html")
def 불광로( request ) :
    return render( request , "불광로.html")
def 수색로( request ) :
    return render( request , "수색로.html")
def 서오릉로( request ) :
    return render( request , "서오릉로.html")
def 은평로( request ) :
    return render( request , "은평로.html")
def 응암로( request ) :
    return render( request , "응암로.html")
def 강서구( request ) :
    return render( request , "강서구.html")
def 강서로( request ) :
    return render( request , "강서로.html")
def 개화로( request ) :
    return render( request , "개화로.html")
def 공항대로( request ) :
    return render( request , "공항대로.html")
def 양천로( request ) :
    return render( request , "양천로.html")
def 허준로( request ) :
    return render( request , "허준로.html")
def 화곡로( request ) :
    return render( request , "화곡로.html")
def 방화대로( request ) :
    return render( request , "방화대로.html")
def 성동구( request ) :
    return render( request , "성동구.html")
def 왕십리로( request ) :
    return render( request , "왕십리로.html")
def 고산자로( request ) :
    return render( request , "고산자로.html")
def 독서당로( request ) :
    return render( request , "독서당로.html")
def 아차산로( request ) :
    return render( request , "아차산로.html")
def 동일로( request ) :
    return render( request , "동일로.html")
def 금호로( request ) :
    return render( request , "금호로.html")
def 영등포구( request ) :
    return render( request , "영등포구.html")
def 당산로( request ) :
    return render( request , "당산로.html")
def 양평로( request ) :
    return render( request , "양평로.html")
def 영중로( request ) :
    return render( request , "영중로.html")
def 경인로( request ) :
    return render( request , "경인로.html")
def 영등포로( request ) :
    return render( request , "영등포로.html")
def 여의나루로( request ) :
    return render( request , "여의나루로.html")
def 신내로( request ) :
    return render( request , "신내로.html")
def 용마산로( request ) :
    return render( request , "용마산로.html")
def 봉화산로( request ) :
    return render( request , "봉화산로.html")
def 망우로( request ) :
    return render( request , "망우로.html")
def 동일로2( request ) :
    return render( request , "동일로2.html")
def view2( request ) :
    return render( request , "view2.html")
def view3( request ) :
    return render( request , "view3.html")
def view4( request ) :
    return render( request , "view4.html")